# Site settings
title: Tong Zhang
email: tz_zju@zju.edu.cn
# description: > # this means to ignore newlines until "baseurl:"
#   I'm a political scientist at Stockholm University with research interests in
#   international conflict and political behavior. Topics on my site include
#   my teaching interests, R, LaTeX, and professional development.
baseurl: "" # the subpath of your site, e.g. /blog/
# twitter_username: stevenvmiller
github_username:  tongzhang111
orcid_id: 0000-0001-8163-3050
google_scholar_id: zThJoqgAAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "PhD Candidate"
excerpt_separator: "<!--more-->"



plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
